import type { Lesson } from "../types";

export const lessons: Lesson[] = [
  {
    id: "learn-k8s-arquitetura",
    track: "kubernetes",
    title: "Arquitetura de um cluster Kubernetes",
    summary: "Control plane, nós e o caminho de um kubectl apply até o container rodando.",
    minutes: 6,
    before: "k8s-cluster-explore",
    blocks: [
      { type: "text", text: "Kubernetes é um sistema **declarativo**: você descreve o estado desejado (\"quero 3 réplicas do nginx:1.25\") e um conjunto de controladores trabalha continuamente para que o estado real convirja para ele." },
      { type: "heading", text: "Control plane × worker nodes" },
      {
        type: "table",
        head: ["Componente", "Onde roda", "Função"],
        rows: [
          ["kube-apiserver", "control plane", "Porta de entrada única. Autentica, autoriza (RBAC), valida e grava no etcd."],
          ["etcd", "control plane", "Banco chave-valor com TODO o estado do cluster. Sem backup, sem cluster."],
          ["kube-scheduler", "control plane", "Escolhe o nó de cada Pod pendente (recursos, taints, afinidade)."],
          ["kube-controller-manager", "control plane", "Loops de reconciliação: Deployment, ReplicaSet, Node, Job…"],
          ["kubelet", "todo nó", "Agente que cria os containers via runtime e reporta status."],
          ["kube-proxy / CNI", "todo nó", "Regras de rede para Services e conectividade entre Pods."],
        ],
      },
      {
        type: "flow",
        steps: [
          { label: "kubectl apply", detail: "envia o manifesto via HTTPS" },
          { label: "API server", detail: "authn → RBAC → admission → etcd" },
          { label: "Controllers", detail: "Deployment cria ReplicaSet, que cria Pods" },
          { label: "Scheduler", detail: "grava `nodeName` no Pod" },
          { label: "kubelet", detail: "puxa a imagem e sobe o container" },
        ],
        caption: "Ninguém \"manda\" o kubelet rodar algo: cada componente observa o API server (watch) e reage.",
      },
      { type: "text", text: "Esse desenho explica muitos sintomas: Pod **Pending sem eventos** aponta para o scheduler; nó **NotReady** aponta para o kubelet; kubectl sem resposta aponta para o API server ou o kubeconfig." },
      { type: "code", lang: "shell", code: "kubectl config current-context   # para qual cluster estou apontando?\nkubectl cluster-info             # API server e CoreDNS respondendo?\nkubectl get nodes -o wide        # nós Ready? versões compatíveis?" },
      { type: "callout", tone: "tip", text: "Em serviços gerenciados (EKS, GKE, AKS) o control plane é do provedor: você não vê os static pods, mas o modelo mental é o mesmo — e o kubelet dos seus nós continua sendo problema seu." },
      { type: "callout", tone: "exam", text: "Na CKA, sempre rode `kubectl config use-context` indicado no enunciado antes de cada questão. Resolver no cluster errado zera a questão." },
    ],
    quiz: [
      { q: "Qual componente grava o estado do cluster de forma persistente?", options: ["kube-apiserver", "etcd", "kube-controller-manager", "kubelet"], answer: 1, explain: "O etcd é o único armazenamento persistente. O API server é o único que conversa com ele." },
      { q: "Um Pod está Pending há minutos e `kubectl describe` não mostra nenhum evento. O que investigar primeiro?", options: ["O registry da imagem", "O kube-scheduler", "O kube-proxy", "O CoreDNS"], answer: 1, explain: "Sem evento de agendamento (nem FailedScheduling), ninguém está avaliando o Pod: o scheduler provavelmente está fora do ar." },
      { q: "Quem efetivamente inicia o container no nó?", options: ["O scheduler", "O API server", "O kubelet, via container runtime", "O controller-manager"], answer: 2, explain: "O scheduler só decide o nó; o kubelet daquele nó observa o Pod atribuído e pede ao runtime (containerd) para criar o container." },
    ],
  },
  {
    id: "learn-k8s-pods",
    track: "kubernetes",
    title: "Pods e o ciclo de vida de um container",
    summary: "O que é um Pod, suas fases e os STATUS que você vai ver no dia a dia.",
    minutes: 6,
    before: "k8s-first-pod",
    blocks: [
      { type: "text", text: "O **Pod** é a menor unidade do Kubernetes: um ou mais containers que compartilham IP, portas e volumes, sempre agendados juntos no mesmo nó. Na prática, 1 Pod = 1 instância da sua aplicação." },
      { type: "code", lang: "yaml", code: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: nginx\n  labels:\n    app: nginx\nspec:\n  containers:\n  - name: nginx\n    image: nginx:1.25\n    ports:\n    - containerPort: 80", caption: "Pod mínimo. Os labels serão usados por Services e Deployments para encontrá-lo." },
      {
        type: "flow",
        steps: [
          { label: "Pending", detail: "aceito pelo API server, esperando nó" },
          { label: "ContainerCreating", detail: "agendado; baixando imagem e montando volumes" },
          { label: "Running", detail: "pelo menos um container em execução" },
          { label: "Succeeded / Failed", detail: "containers terminaram (Jobs)" },
        ],
      },
      { type: "heading", text: "STATUS que você precisa reconhecer" },
      {
        type: "table",
        head: ["STATUS", "O que significa", "Primeiro comando"],
        rows: [
          ["ImagePullBackOff", "Não conseguiu baixar a imagem (nome, tag, registry privado)", "`kubectl describe pod`"],
          ["CrashLoopBackOff", "O container sobe e morre repetidamente", "`kubectl logs --previous`"],
          ["CreateContainerConfigError", "ConfigMap/Secret referenciado não existe", "`kubectl describe pod`"],
          ["Pending", "Sem nó disponível ou scheduler parado", "`kubectl describe pod` (FailedScheduling)"],
          ["Running 0/1", "Vivo, mas reprovado na readiness probe", "`kubectl describe pod` (Unhealthy)"],
        ],
      },
      { type: "callout", tone: "warn", text: "Pods criados diretamente não se recuperam: se o nó morrer, o Pod some. Em produção, sempre use um controller (Deployment, StatefulSet, DaemonSet, Job)." },
      { type: "callout", tone: "exam", text: "`kubectl run nome --image=img --dry-run=client -o yaml > pod.yaml` gera o esqueleto em segundos. Decore esse atalho." },
    ],
    quiz: [
      { q: "Containers do mesmo Pod compartilham…", options: ["Apenas o nó", "IP, portas e volumes declarados", "Nada — são isolados como Pods diferentes", "Somente variáveis de ambiente"], answer: 1, explain: "Eles compartilham o namespace de rede (mesmo IP, falam via localhost) e podem montar os mesmos volumes." },
      { q: "Um Pod está em CrashLoopBackOff. Onde está a causa, normalmente?", options: ["Nos logs da execução anterior do container", "No etcd", "No kube-proxy", "No registry da imagem"], answer: 0, explain: "O container iniciou e terminou; a mensagem de erro está nos logs da execução que morreu (`--previous`)." },
      { q: "Qual STATUS indica problema para baixar a imagem?", options: ["CreateContainerConfigError", "ImagePullBackOff", "Completed", "OOMKilled"], answer: 1, explain: "ErrImagePull/ImagePullBackOff: nome/tag errados, registry privado sem imagePullSecret ou rate limit." },
    ],
  },
  {
    id: "learn-k8s-deployments",
    track: "kubernetes",
    title: "Deployments, ReplicaSets e o loop de reconciliação",
    summary: "Como o Kubernetes mantém N réplicas vivas e faz atualizações sem downtime.",
    minutes: 6,
    before: "k8s-deploy",
    blocks: [
      { type: "text", text: "Um **Deployment** declara o template do Pod e quantas réplicas você quer. Ele cria um **ReplicaSet** por versão do template, e o ReplicaSet garante que existam exatamente N Pods daquela versão." },
      {
        type: "flow",
        steps: [
          { label: "Estado desejado", detail: "replicas: 3" },
          { label: "Observa", detail: "ReplicaSet conta 2 Pods prontos" },
          { label: "Compara", detail: "faltam 1" },
          { label: "Age", detail: "cria 1 Pod novo" },
        ],
        caption: "O loop de reconciliação roda o tempo todo — é por isso que apagar um Pod de um Deployment não \"quebra\" nada.",
      },
      { type: "heading", text: "Rolling update" },
      { type: "text", text: "Ao mudar a imagem, o Deployment cria um ReplicaSet novo e vai trocando Pods gradualmente, controlado por dois parâmetros:" },
      {
        type: "table",
        head: ["Parâmetro", "Padrão", "Efeito"],
        rows: [
          ["maxSurge", "25%", "Quantos Pods ACIMA do desejado podem existir durante a troca"],
          ["maxUnavailable", "25%", "Quantos Pods podem ficar indisponíveis durante a troca"],
          ["revisionHistoryLimit", "10", "Quantos ReplicaSets antigos guardar para rollback"],
        ],
      },
      { type: "code", lang: "shell", code: "kubectl create deployment web --image=nginx:1.25 --replicas=3\nkubectl set image deployment/web web=nginx:1.26\nkubectl rollout status deployment/web\nkubectl rollout undo deployment/web" },
      { type: "callout", tone: "tip", text: "Sem readiness probe, o rolling update considera o Pod pronto assim que o container sobe — e pode mandar tráfego para uma app que ainda está carregando." },
      { type: "callout", tone: "exam", text: "Pergunta clássica de entrevista: \"qual a diferença entre ReplicaSet e Deployment?\" — o ReplicaSet mantém a contagem; o Deployment gerencia versões (rollouts e rollbacks) criando ReplicaSets." },
    ],
    quiz: [
      { q: "Você apaga um Pod que pertence a um Deployment com 3 réplicas. O que acontece?", options: ["O Deployment fica com 2 réplicas", "O ReplicaSet cria um Pod novo para voltar a 3", "O Deployment é apagado", "Nada até o próximo deploy"], answer: 1, explain: "O ReplicaSet observa 2 Pods em vez de 3 e cria um novo imediatamente." },
      { q: "O que um rollback (`rollout undo`) faz internamente?", options: ["Reinstala a imagem antiga no mesmo Pod", "Reescala o ReplicaSet da revisão anterior e zera o atual", "Restaura um backup do etcd", "Recria o Deployment do zero"], answer: 1, explain: "Os ReplicaSets antigos ficam guardados com 0 réplicas; o rollback só inverte as escalas — por isso é tão rápido." },
      { q: "Com replicas=4, maxSurge=25% e maxUnavailable=0, quantos Pods podem existir no máximo durante o update?", options: ["4", "5", "6", "8"], answer: 1, explain: "25% de 4 = 1 Pod extra; com maxUnavailable 0, nunca cai abaixo de 4 e sobe no máximo até 5." },
    ],
  },
  {
    id: "learn-k8s-services",
    track: "kubernetes",
    title: "Services, DNS e como o tráfego chega ao Pod",
    summary: "ClusterIP, NodePort, LoadBalancer e o papel dos Endpoints.",
    minutes: 6,
    before: "k8s-expose",
    blocks: [
      { type: "text", text: "Pods são efêmeros e mudam de IP a cada recriação. Um **Service** dá um nome DNS e um IP virtual estáveis, e balanceia entre os Pods selecionados por **labels**." },
      {
        type: "flow",
        steps: [
          { label: "DNS", detail: "`web.default.svc.cluster.local`" },
          { label: "ClusterIP", detail: "IP virtual do Service" },
          { label: "kube-proxy", detail: "regras iptables/IPVS em cada nó" },
          { label: "Endpoints", detail: "IPs dos Pods prontos que casam com o selector" },
          { label: "Pod", detail: "targetPort do container" },
        ],
      },
      {
        type: "table",
        head: ["Tipo", "Acessível de", "Uso típico"],
        rows: [
          ["ClusterIP", "Dentro do cluster", "Comunicação entre microserviços (padrão)"],
          ["NodePort", "IP de qualquer nó : 30000-32767", "Laboratório, integrações simples"],
          ["LoadBalancer", "Internet / VPC", "Provisiona NLB/ELB no provedor de nuvem"],
          ["Ingress (não é Service)", "HTTP/HTTPS por host e path", "ALB/ingress-nginx na frente de vários Services"],
        ],
      },
      { type: "code", lang: "shell", code: "kubectl expose deployment web --port=80 --type=NodePort\nkubectl get endpoints web     # para onde o tráfego vai?\nkubectl run tmp --rm -it --image=busybox --restart=Never -- wget -qO- web" },
      { type: "callout", tone: "warn", text: "Endpoints `<none>` com Pods saudáveis = selector não casa com os labels (um typo basta). O Service é criado sem erro nenhum." },
      { type: "callout", tone: "exam", text: "Nomes DNS de Service só resolvem DENTRO do cluster. Para testar, use um Pod temporário (`kubectl run --rm -it`), não o terminal do nó." },
    ],
    quiz: [
      { q: "Como um Service sabe para quais Pods mandar tráfego?", options: ["Pelo nome do Deployment", "Pelo selector de labels, filtrando Pods prontos", "Pelo namespace inteiro", "Pelo IP que você cadastra manualmente"], answer: 1, explain: "O endpoint controller lista os Pods cujo label casa com o selector e que passaram na readiness." },
      { q: "Qual tipo de Service expõe uma porta alta em todos os nós?", options: ["ClusterIP", "NodePort", "ExternalName", "Headless"], answer: 1, explain: "NodePort abre a mesma porta (30000-32767) em todos os nós e encaminha para o Service." },
      { q: "Pods Running e prontos, mas o Service não responde e Endpoints está vazio. Causa mais provável?", options: ["CoreDNS fora", "Selector do Service diferente dos labels dos Pods", "Imagem errada", "Falta de CPU"], answer: 1, explain: "Endpoints vazio com Pods prontos quase sempre é selector/labels divergentes." },
    ],
  },
  {
    id: "learn-k8s-troubleshooting",
    track: "kubernetes",
    title: "Método de troubleshooting em Kubernetes",
    summary: "Do sintoma à causa raiz com get, describe, logs e events — sem chutar.",
    minutes: 5,
    before: "k8s-troubleshoot-nginx",
    blocks: [
      { type: "text", text: "Incidentes em Kubernetes quase sempre se resolvem com o mesmo roteiro. A disciplina de seguir a ordem evita \"consertar\" a coisa errada sob pressão." },
      {
        type: "flow",
        steps: [
          { label: "get", detail: "qual o STATUS? quantos prontos?" },
          { label: "describe", detail: "Events: o que o cluster tentou e falhou" },
          { label: "logs", detail: "o que a aplicação disse (use --previous)" },
          { label: "corrigir", detail: "a menor mudança que resolve a causa" },
          { label: "validar", detail: "rollout status, endpoints, curl" },
        ],
      },
      {
        type: "list",
        items: [
          "**Sintoma ≠ causa**: ImagePullBackOff é sintoma; \"typo no nome da imagem\" é causa.",
          "Leia os **Events** de baixo para cima: o último evento costuma ser o mais relevante.",
          "Confirme a hipótese antes de mudar algo — e mude uma coisa de cada vez.",
          "Termine sempre validando do ponto de vista do usuário (requisição real).",
        ],
      },
      { type: "code", lang: "shell", code: "kubectl get pods -o wide\nkubectl describe pod <pod> | tail -20\nkubectl logs <pod> --previous\nkubectl get events --sort-by=.lastTimestamp" },
      { type: "callout", tone: "tip", text: "Em produção, registre o que viu e fez durante o incidente (timeline). Isso vira o post-mortem e evita repetir o problema." },
      { type: "callout", tone: "exam", text: "Em entrevistas de SRE, narrar esse método em voz alta (\"primeiro olho o status, depois os eventos…\") vale tanto quanto acertar a causa." },
    ],
    quiz: [
      { q: "O Pod está ImagePullBackOff. Qual comando mostra o motivo exato?", options: ["kubectl logs", "kubectl describe pod", "kubectl top pod", "kubectl get svc"], answer: 1, explain: "O container nem iniciou, então não há logs; os Events do describe mostram o erro do pull." },
      { q: "Por que usar `kubectl logs --previous` em CrashLoopBackOff?", options: ["Porque mostra os logs do container que morreu", "Porque é mais rápido", "Porque mostra os logs do nó", "Porque ignora erros"], answer: 0, explain: "O container atual pode estar reiniciando sem ter logado nada; a causa está na execução anterior." },
      { q: "Qual é o último passo do método?", options: ["Apagar o Pod", "Validar do ponto de vista do usuário", "Aumentar as réplicas", "Reiniciar o nó"], answer: 1, explain: "Sem validação (rollout status, endpoints, requisição real) você não sabe se o incidente acabou." },
    ],
  },
];
